// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmpumggummpotwkzhalw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcHVtZ2d1bW1wb3R3a3poYWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODA5ODYsImV4cCI6MjA3MDU1Njk4Nn0.p_kqTBYLMVhT9YoLDmeD29jnRef_Cx195OwCprp0ekU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});